# Generated by Django 6.0.3 on 2026-03-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('PCS', 'Pieces (pcs)'), ('KG', 'Kilograms (kg)'), ('L', 'Liters (L)'), ('G', 'Grams (g)'), ('PKT', 'Packets (pkt)'), ('BTL', 'Bottles (btl)')], default='PCS', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
