# Generated by Django 6.0.3 on 2026-03-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_unit_alter_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
