# Generated by Django 6.0.3 on 2026-03-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_low_stock_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='buy_price',
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stock')),
            ],
        ),
    ]
