# Generated by Django 6.0.3 on 2026-03-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transaction_transactionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
