# Generated by Django 6.0.3 on 2026-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_stock_buy_price_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='StockBatch',
        ),
    ]
