# Generated by Django 6.0.3 on 2026-03-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='current_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
